### ISSUE TITLE
Error about shareOptions

### ISSUE THREAD

**Issue by couranos** [ShekarMudaliyar/social_share#20]
E/MethodChannel#social_share(16149): Failed to handle method call
E/MethodChannel#social_share(16149): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND flg=0x1 clip={null T:Hello world} (has extras) }
E/MethodChannel#social_share(16149): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
E/MethodChannel#social_share(16149): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
E/MethodChannel#social_share(16149): 	at android.app.Activity.startActivityForResult(Activity.java:4225)
E/MethodChannel#social_share(16149): 	at android.app.Activity.startActivityForResult(Activity.java:4183)
E/MethodChannel#social_share(16149): 	at android.app.Activity.startActivity(Activity.java:4522)
E/MethodChannel#social_share(16149): 	at android.app.Activity.startActivity(Activity.java:4490)
E/MethodChannel#social_share(16149): 	at com.shekarmudaliyar.social_share.SocialSharePlugin.onMethodCall(SocialSharePlugin.kt:116)
E/MethodChannel#social_share(16149): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#social_share(16149): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#social_share(16149): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#social_share(16149): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#social_share(16149): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#social_share(16149): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#social_share(16149): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/MethodChannel#social_share(16149): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#social_share(16149): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#social_share(16149): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/flutter (16149): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.intent.action.SEND flg=0x1 clip={null T:Hello world} (has extras) }, null)

**Comment by ShekarMudaliyar** [comment]
can u also provide the code ?

**Comment by luismarga** [comment]
Hi Shekar, thanks for your code, the error that i have is when i use this code dont work

```
SocialShare.shareOptions("Hello world").then((data) {print(data); });
```
but if i use this 

`await screenshotController.capture().then((image) async {
                      SocialShare.shareOptions("Hello world",
                              imagePath: image.path)
                          .then((data) {
                        print(data);
                      });
                    });` it works fine

which could be the error?

**Comment by ShekarMudaliyar** [comment]
@NWalker1208 has fixed the issue
You can try the new version out it will work without the image as well
