### ISSUE TITLE
Error in the provider, to the to share image in more options

### ISSUE THREAD

**Issue by giovannilima262** [ShekarMudaliyar/social_share#46]
This error is printed when sharing the image in other options, but the sharing is working normally. However the image of the sharing popup does not appear and this error is demonstrated.

E/DatabaseUtils(28615): Writing exception to parcel
E/DatabaseUtils(28615): java.lang.SecurityException: Permission Denial: reading com.example.mobile_app.FlutterSocialSharePluginFileProvider uri content://com.po.po_mobile_app.com.shekarmudaliyar.social_share/image/stickerAsset.png from pid=29565, uid=1000 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils(28615): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
E/DatabaseUtils(28615): 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
E/DatabaseUtils(28615): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
E/DatabaseUtils(28615): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:593)
E/DatabaseUtils(28615): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:507)
E/DatabaseUtils(28615): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:307)
E/DatabaseUtils(28615): 	at android.os.Binder.execTransactInternal(Binder.java:1056)

`flutter doctor`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

**Comment by jordanliu** [comment]
Did you find a fix for this? @giovannilima262
